// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CrnewlHie0ky08yUAjFZnkA2d8K_msU',
    appId: '1:775623387193:web:8ee85753d75f3cefc945e8',
    messagingSenderId: '775623387193',
    projectId: 'firesome-2297e',
    authDomain: 'firesome-2297e.firebaseapp.com',
    storageBucket: 'firesome-2297e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBiWzW-AI13CwTdf_VjVjTOmKs4C_i_n0',
    appId: '1:775623387193:android:57774764d8011a21c945e8',
    messagingSenderId: '775623387193',
    projectId: 'firesome-2297e',
    storageBucket: 'firesome-2297e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgKlkAF2Iyx5crbCpvy_XChhUrZpGY4L4',
    appId: '1:775623387193:ios:5716eac25ad6acbbc945e8',
    messagingSenderId: '775623387193',
    projectId: 'firesome-2297e',
    storageBucket: 'firesome-2297e.appspot.com',
    iosClientId: '775623387193-356mvfqmipn4lfkbf3vmvf29httioab9.apps.googleusercontent.com',
    iosBundleId: 'com.testing.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgKlkAF2Iyx5crbCpvy_XChhUrZpGY4L4',
    appId: '1:775623387193:ios:c9af16efbe9b2855c945e8',
    messagingSenderId: '775623387193',
    projectId: 'firesome-2297e',
    storageBucket: 'firesome-2297e.appspot.com',
    iosClientId: '775623387193-k5ablq4u1i8dr6t6mt4id7190vuaumit.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );
}
